### PR TITLE
Start YAML output with ---, always

### LINKED ISSUE #16: Start YAML output with `---`
Background:
I use `kbld` to dynamically replace docker `image:tag` notations with `image:digest` before applying the manifests in a pipeline like this:

`custom-script-to-render-multiple-helm-charts | kbld -f - | kubectl apply -f -`

According to the [YAML spec](https://yaml.org/spec/1.2/spec.html#id2760395) a YAML document _may_ start with `---`. 
Adding `---` on the top of every YAML file (even empty ones) has proven specifically useful when concatenating the output of tools like `kubectl`, `helm template` and also `kbld` into a single file and is hence somewhat considered a best practice (at least in my filter-bubble).

`kbld` does not (yet) add `---` on top of its output by default and does not have an option to enable it either. It would be really helpful to have it.

I am happy to provide a PR if you pointed me in the right direction.

### PR DESCRIPTION
**Pull request by dsiebel**
fixes #16

I have not signed the CLA, yet. Just outlining what the "fix" could look like to get some feedback.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@dsiebel Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=k14s/kbld&pullRequestId=17)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=k14s/kbld&pullRequestId=17) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by cppforlife** [comment]
@dsiebel thanks for the PR (im back from vacation/move-across-country). would you mind signing CLA above?

**Comment by dsiebel** [comment]
> @dsiebel thanks for the PR (im back from vacation/move-across-country). would you mind signing CLA above?

I need permission from my employer to sign it. German law is quite specific when it comes to copyright and software. I am currently waiting for feedback.

**Comment by cppforlife** [comment]
> I need permission from my employer to sign it. German law is quite specific when it comes to copyright and software. I am currently waiting for feedback.

just checking in how it's going. do you need this change included in kbld in a short term? if so, i can "reimplement" it.

**Comment by pivotal-issuemaster** [comment]
@dsiebel Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=k14s/kbld&pullRequestId=17)!

**Comment by dsiebel** [comment]
> > I need permission from my employer to sign it. German law is quite specific when it comes to copyright and software. I am currently waiting for feedback.
> 
> just checking in how it's going. do you need this change included in kbld in a short term? if so, i can "reimplement" it.

Hey @cppforlife, I finally got the approval to sign.

**Pull request merged**
